# Generated by Django 2.2.2 on 2019-06-12 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sale', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='in_escrow',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='sale',
            name='completed',
            field=models.BooleanField(default=False),
        ),
    ]
