# Generated by Django 2.2.2 on 2019-06-14 05:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sale', '0003_auto_20190614_0412'),
    ]

    operations = [
        migrations.CreateModel(
            name='SaleImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='')),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='images', to='sale.Sale')),
            ],
        ),
    ]
