# Generated by Django 2.2.2 on 2019-06-12 02:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sale',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=200)),
                ('city', models.CharField(default='Culver City', max_length=50)),
                ('zipcode', models.DecimalField(decimal_places=0, default=0, max_digits=5)),
                ('longitude', models.DecimalField(decimal_places=7, default=0, max_digits=10)),
                ('latitude', models.DecimalField(decimal_places=7, default=0, max_digits=10)),
                ('price_per_month', models.IntegerField(default=0)),
                ('featured', models.BooleanField(default=False)),
                ('lot_size', models.IntegerField(blank=True, default=0)),
                ('building_size', models.IntegerField(default=0)),
                ('lease_type', models.CharField(choices=[('NNN', 'NNN'), ('MG', 'MG')], max_length=10)),
                ('completed', models.BooleanField()),
                ('description', models.CharField(max_length=400)),
                ('main_image', models.ImageField(upload_to='images')),
                ('flier', models.FileField(upload_to='fliers')),
            ],
        ),
    ]
