# Generated by Django 2.2.2 on 2019-06-14 04:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lease', '0004_auto_20190614_0412'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lease',
            name='featured',
        ),
    ]
