# Generated by Django 2.2.2 on 2019-06-21 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lease', '0004_auto_20190621_0331'),
    ]

    operations = [
        migrations.AddField(
            model_name='lease',
            name='main_image_description',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
