# Generated by Django 2.2.2 on 2019-06-22 15:57

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lease', '0005_lease_main_image_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lease',
            name='completion_date',
            field=models.DateField(blank=True, default=datetime.date(2019, 6, 22)),
        ),
        migrations.CreateModel(
            name='LeaseImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='')),
                ('imagedescription', models.CharField(blank=True, max_length=100)),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='images', to='lease.Lease')),
            ],
        ),
    ]
