# Generated by Django 2.2.2 on 2019-06-23 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lease', '0008_auto_20190623_1708'),
    ]

    operations = [
        migrations.AddField(
            model_name='lease',
            name='featured',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
