# Generated by Django 2.2.2 on 2019-07-04 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lease', '0009_lease_featured'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lease',
            name='main_image',
            field=models.ImageField(upload_to='images/'),
        ),
    ]
