# Generated by Django 2.2.2 on 2019-07-14 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lease', '0010_auto_20190704_2001'),
    ]

    operations = [
        migrations.AddField(
            model_name='leaseimage',
            name='rank',
            field=models.IntegerField(default=1),
        ),
    ]
