# Generated by Django 2.2.2 on 2019-07-04 20:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transactioncount',
            old_name='leaded',
            new_name='leased',
        ),
    ]
