# Generated by Django 2.2.2 on 2019-06-14 04:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lease', '0003_auto_20190614_0326'),
    ]

    operations = [
        migrations.AddField(
            model_name='lease',
            name='in_escrow',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='lease',
            name='completed',
            field=models.BooleanField(default=False),
        ),
    ]
