# Generated by Django 2.2.2 on 2019-06-16 02:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sale', '0002_auto_20190612_0609'),
    ]

    operations = [
        # migrations.CreateModel(
        #     name='SaleImage',
        #     fields=[
        #         ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
        #         ('image', models.ImageField(upload_to='')),
        #         ('property', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='images', to='sale.Sale')),
        #     ],
        # ),
    ]
