# Generated by Django 2.2.2 on 2019-06-16 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sale', '0003_saleimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='property_type',
            field=models.CharField(default='Owner/User', max_length=40),
        ),
        migrations.AlterField(
            model_name='sale',
            name='main_image',
            field=models.ImageField(upload_to='images/'),
        ),
    ]
