# Generated by Django 2.2.2 on 2019-06-21 03:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sale', '0004_auto_20190616_0626'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sale',
            name='building_size',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='sale',
            name='completed',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name='sale',
            name='description',
            field=models.CharField(blank=True, max_length=400),
        ),
        migrations.AlterField(
            model_name='sale',
            name='featured',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name='sale',
            name='flier',
            field=models.FileField(blank=True, upload_to='fliers/'),
        ),
        migrations.AlterField(
            model_name='sale',
            name='in_escrow',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name='sale',
            name='main_image',
            field=models.ImageField(blank=True, upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='sale',
            name='price',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='sale',
            name='property_type',
            field=models.CharField(blank=True, default='Owner/User', max_length=40),
        ),
    ]
