# Generated by Django 2.2.2 on 2019-06-21 03:31

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sale', '0005_auto_20190621_0320'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='completion_date',
            field=models.DateField(blank=True, default=datetime.date(2019, 6, 21)),
        ),
        migrations.AddField(
            model_name='sale',
            name='rank',
            field=models.IntegerField(default=1),
        ),
    ]
