# Generated by Django 2.2.2 on 2019-06-21 20:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sale', '0006_auto_20190621_0331'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='main_image_description',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
