# Generated by Django 2.2.2 on 2019-06-22 15:57

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sale', '0008_saleimage_imagedescription'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sale',
            name='completion_date',
            field=models.DateField(blank=True, default=datetime.date(2019, 6, 22)),
        ),
    ]
