# Generated by Django 2.2.2 on 2019-06-23 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sale', '0010_auto_20190622_1609'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sale',
            name='completion_date',
            field=models.DateField(blank=True),
        ),
    ]
