# Generated by Django 2.2.2 on 2019-07-04 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sale', '0011_auto_20190623_1708'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sale',
            name='main_image',
            field=models.ImageField(upload_to='images/'),
        ),
    ]
