# Generated by Django 2.2.2 on 2019-06-15 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('completedtransactions', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='completedtransactions',
            name='city',
        ),
        migrations.RemoveField(
            model_name='completedtransactions',
            name='zipcode',
        ),
        migrations.AddField(
            model_name='completedtransactions',
            name='transaciton_type',
            field=models.CharField(default='Owner/User', max_length=30),
        ),
    ]
