# Generated by Django 2.2.2 on 2019-06-15 17:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('completedtransactions', '0002_auto_20190615_1741'),
    ]

    operations = [
        migrations.RenameField(
            model_name='completedtransactions',
            old_name='transaciton_type',
            new_name='transaction_type',
        ),
    ]
