# Generated by Django 2.2.2 on 2019-06-16 06:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('completedtransactions', '0004_completedtransactionssearch'),
    ]

    operations = [
        migrations.RenameField(
            model_name='completedtransactions',
            old_name='transaction_type',
            new_name='property_type',
        ),
        migrations.DeleteModel(
            name='CompletedTransactionsSearch',
        ),
    ]
