# Generated by Django 2.2.2 on 2019-06-23 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('completedtransactions', '0006_completedtransactions_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='completedtransactions',
            name='category',
            field=models.CharField(choices=[(1, 'Venice'), (2, 'Sepulveda'), (3, 'Washington'), (4, 'LaCienega'), (5, 'Overland'), (6, 'Robertson'), (7, 'Jefferson'), (8, 'W. Adams'), (9, 'Dunn'), (10, 'Other')], default='1', max_length=40),
        ),
    ]
