# Generated by Django 2.2.2 on 2019-07-04 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('completedtransactions', '0007_auto_20190623_2042'),
    ]

    operations = [
        migrations.AlterField(
            model_name='completedtransactions',
            name='category',
            field=models.CharField(choices=[('a', 'Venice'), ('b', 'Sepulveda'), ('c', 'Washington'), ('d', 'LaCienega'), ('e', 'Overland'), ('f', 'Robertson'), ('g', 'Jefferson'), ('h', 'W. Adams'), ('i', 'Dunn'), ('j', 'Other')], default='a', max_length=40),
        ),
    ]
